version: "3.7"

services:
  whitelister:
    container_name: whitelister
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    environment:
      - APP_ENV=local
    stop_signal: SIGINT
    volumes:
      - ./..:/go/src/whitelister
    ports:
      - 8080:8080
    networks:
      - whitelister-net

  tests:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    working_dir: /var/www/whitelister
    command: go test -v ./...
    volumes:
      - ./..:/var/www/whitelister

  linter:
    image: golangci/golangci-lint:latest
    working_dir: /app
    command: golangci-lint run -v
    volumes:
      - ./..:/app

networks:
  whitelister-net:
    driver: bridge